name: Deploy and Sync DB

on:
  workflow_dispatch:  # 這樣可以手動觸發，並且 Render Webhook 發送後會啟動這個流程

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Sync db.json to repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add db.json
        git commit -m "Update db.json from Render"
        git push origin main  # 推送回你的主分支
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token
